// <auto-generated />
using System;
using ECommerceBrazorNet7.Repository.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceBrazorNet7.Repository.Migrations
{
    [DbContext(typeof(DbecommerceContext))]
    partial class DbecommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NameCategory")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCategory")
                        .HasName("PK__Category__CBD7470656E4333D");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("NameProduct")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("OfferPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Picture")
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdProduct")
                        .HasName("PK__Product__2E8946D4A9CE6714");

                    b.HasIndex("IdCategory");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Sale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdSale")
                        .HasName("PK__Sale__A04F9B379C9168FF");

                    b.HasIndex("IdUser");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.SalesDetail", b =>
                {
                    b.Property<int>("IdSalesDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int?>("IdSale")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdSalesDetail")
                        .HasName("PK__SalesDet__3388DAF143CA7770");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSale");

                    b.ToTable("SalesDetail", (string)null);
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUser")
                        .HasName("PK__Users__B7C926388D2AF984");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Product", b =>
                {
                    b.HasOne("ECommerceBrazorNet7.Model.Category", "IdCategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .HasConstraintName("FK__Product__IdCateg__4CA06362");

                    b.Navigation("IdCategoryNavigation");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Sale", b =>
                {
                    b.HasOne("ECommerceBrazorNet7.Model.User", "IdUserNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__Sale__idUser__534D60F1");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.SalesDetail", b =>
                {
                    b.HasOne("ECommerceBrazorNet7.Model.Product", "IdProductNavigation")
                        .WithMany("SalesDetails")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK__SalesDeta__IdPro__5812160E");

                    b.HasOne("ECommerceBrazorNet7.Model.Sale", "IdSaleNavigation")
                        .WithMany("SalesDetails")
                        .HasForeignKey("IdSale")
                        .HasConstraintName("FK__SalesDeta__IdSal__571DF1D5");

                    b.Navigation("IdProductNavigation");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Product", b =>
                {
                    b.Navigation("SalesDetails");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.Sale", b =>
                {
                    b.Navigation("SalesDetails");
                });

            modelBuilder.Entity("ECommerceBrazorNet7.Model.User", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
